version: '1.0'
services:
  mauth_app:
    image: "geos74/mauth:1.1.0"
    environment:
      - NODE_ENV=prod
      - SERVER_PORT=3001
      - DB_USER=mauth
      - DB_HOST=db_mauth
      - DB_NAME=mauth
      - DB_PASS=${POSTGRES_PASSWORD}
      - JWT_TTL=180
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - VERIFICATION_TTL=10 minute
      - VERIFICATION_IGNORE=true
      - SESSION_TTL=7 day
      - REGISTRATION_PROHIBITED=true
    volumes:
      - init-db-mauth:/mauth/libs
    restart: on-failure
  db_mauth:
    image: "postgres"
    volumes:
      - init-db-mauth:/docker-entrypoint-initdb.d
      - db-mauth:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=mauth
      - POSTGRES_DB=mauth
    restart: on-failure
  cr_info_app:
    image: "geos74/car-repair-info:0.0.4"
    environment:
      - NODE_ENV=prod
      - SERVER_PORT=3020
      - DB_USER=root
      - DB_PASS=${MONGO_DB_PASS}
      - DB_HOST=db_cr_info
      - DB_PORT=27017
      - DB_NAME=admin
      - CREATE_AUTOINDEX=true
      - JWT_CHECK=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - files-db_cr_info:/car-repair-info/files
      - init-db_cr_info:/car-repair-info/libs/db.init
    restart: on-failure
  db_cr_info:
    image: "mongo"
    volumes:
      - db_cr_info:/data/db
      - init-db_cr_info:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASS}
      - MONGO_INITDB_DATABASE=admin
    restart: on-failure
  main:
    image: "geos74/car-repair:0.0.6"
    ports:
      - "80:80"
    volumes:
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
volumes:
  init-db-mauth:
  db-mauth:
  files-db_cr_info:
  init-db_cr_info:
  db_cr_info:
